### PR TITLE
Move finalization logic into termination of BackgroundThread

### LINKED ISSUE #642: Horovod hangs on shutdown when a rank crashes
# Environment
MPI Versions: 3.0.0, 3.1.2, & 4.0.0
Pytorch 0.4.1 & Tensorflow 1.8.0
Python 2.7

# Minimal Example
```python
from __future__ import print_function

import atexit
import sys
import time
try:
  import horovod.torch as hvd
except ImportError:
  import horovod.tensorflow as hvd

if __name__ == '__main__':
  print('initializing')
  hvd.init()
  # Uncomment this to achieve the expected behavior
  # atexit._exithandlers = []
  time.sleep(3)
  print('initialized')
  if hvd.rank() == 0:
    time.sleep(10)
    print('exiting!')
    sys.exit(1)
  else:
    print('Sleeping for', sys.argv[1])
    time.sleep(int(sys.argv[1]))
    print('done')
```

## Behavior
After rank 0 exits, rank 1 continues to sleep. When rank 1 finishes sleeping, it prints `done` and mpi exits with an error. 

```bash
$ mpirun -mca btl ^tcp -np 2 python sleep.py 50
initializing
initializing
initialized
Sleeping for 30
initialized
exiting!
done
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[39251,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

## Expected Behavior 
When rank 0 crashes it should shut down all mpi processes. Rank 1 should never print `done`. This can be achieved by uncommenting the atexit handler in the above example. 
```bash
$ mpirun -mca btl ^tcp -np 2 python sleep.py 50
initializing
initializing
initialized
Sleeping for 50
initialized
exiting!
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[42321,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

## Gdb Backtrace
This is the backtrace on the rank 0 process after rank 0 has exited and while rank 1 is sleeping. It looks like `ompi_mpi_finalize` polling for some event, but it is hard to tell.
```
(gdb) bt
#0  0x00007f118e20430d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f118e235d94 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x00007f114abb9ea7 in ompi_mpi_finalize () from /usr/local/lib/libmpi.so.40
#3  0x00007f114aed81ef in horovod::common::horovod_shutdown () at /tmp/pip-install-SZ9jbr/horovod/horovod/common/operations.cc:1981
#4  0x00007f118d3e9e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#5  0x00007f118d3e98ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#6  0x00007f118d5f93df in _ctypes_callproc () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#7  0x00007f118d5fdd82 in ?? () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#8  0x00000000004c166d in PyEval_EvalFrameEx ()
#9  0x00000000004b9b66 in PyEval_EvalCodeEx ()
#10 0x00000000004d57a3 in ?? ()
#11 0x00000000004a587e in PyObject_Call ()
#12 0x00000000004be51e in PyEval_EvalFrameEx ()
#13 0x00000000004b9b66 in PyEval_EvalCodeEx ()
#14 0x00000000004d5669 in ?? ()
#15 0x00000000004a587e in PyObject_Call ()
#16 0x00000000004c5f3d in PyEval_CallObjectWithKeywords ()
#17 0x00000000004351ad in ?? ()
#18 0x000000000051ea38 in Py_Exit ()
#19 0x000000000051bfd7 in ?? ()
#20 0x000000000051b8fd in PyErr_PrintEx ()
#21 0x0000000000430c25 in ?? ()
#22 0x00000000004938ce in Py_Main ()
#23 0x00007f118e158830 in __libc_start_main (main=0x493370 <main>, argc=3, argv=0x7ffd289908b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd289908a8) at ../csu/libc-start.c:291
#24 0x0000000000493299 in _start ()
```

## Python Backtrace
```
Stack for thread 139999936075520
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "<string>", line 167, in run
  File "/usr/lib/python2.7/code.py", line 243, in interact
    more = self.push(line)
  File "/usr/lib/python2.7/code.py", line 265, in push
    more = self.runsource(source, self.filename)
  File "/usr/lib/python2.7/code.py", line 87, in runsource
    self.runcode(code)
  File "/usr/lib/python2.7/code.py", line 103, in runcode
    exec code in self.locals
  File "<console>", line 3, in <module>

Stack for thread 140000023533312
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/horovod/common/__init__.py", line 88, in shutdown
    return self.MPI_LIB_CTYPES.horovod_shutdown()
```

Is this the expected behavior?

### PR DESCRIPTION
**Pull request by alsrgv**
Fixes #642

### CODE REVIEW

File: horovod/common/operations.cc [hunk 1]
```diff
@@ -1956,36 +1989,6 @@ void horovod_shutdown() {
     horovod_global.initialize_flag.clear();
     horovod_global.shut_down = false;
   }
-
-  if (horovod_global.mpi_comm != MPI_COMM_NULL &&
-      horovod_global.mpi_comm != MPI_COMM_WORLD) {
-    MPI_Comm_free(&horovod_global.mpi_comm);
```
Comment (alsrgv) [inline horovod/common/operations.cc]: @vloncar, do you remember why this logic ended up in `horovod_shutdown()` instead of `BackgroundThread` code?

Comment (vloncar) [reply horovod/common/operations.cc]: @alsrgv The original idea was to to move the `MPI_Finalize()` out of the `BackgroundThread` so that if Horovod is embedded into a larger MPI application it won't stop everything once it finishes thus allowing for restarts (a repeat of `hvd.init()` & `hvd.shutdown()` sequence in a larger MPI app). Later refinements have added the ability for Horovod to figure out if it needs to call `MPI_Finalize()` or just free up internal communicators, so yeah, it doesn't really need to be done in `shutdown()`. I vaguely remember there being some issues with MPI finalizing in one background thread if background threads on other ranks are still communicating, but I can't reproduce those issues with this. I have tested your change in our apps, and it works as expected, so LGTM.
